# Generated by Django 3.2.17 on 2023-03-09 16:05

from django.db import migrations, models
import grimoirelab_toolkit.datetime
import sortinghat.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_sortinghat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIdentitiesTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sortinghat.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', sortinghat.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('backend', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('interval', models.PositiveIntegerField()),
                ('args', models.JSONField(null=True)),
                ('job_id', models.CharField(max_length=128)),
                ('last_execution', models.DateTimeField(default=None, null=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('executions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'import_identities_task',
                'unique_together': {('backend', 'url')},
            },
        ),
    ]
