# Generated by Django 3.2.17 on 2023-03-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_importidentitiestask'),
    ]

    operations = [
        migrations.AddField(
            model_name='importidentitiestask',
            name='scheduled_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importidentitiestask',
            name='job_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
